{"level":"error","message":"failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"error"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}] MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"Error: MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at module.exports (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\startup\\db.js:21:11)"}
{"level":"error","message":"failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"error"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}] MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"Error: MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at module.exports (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\startup\\db.js:21:11)"}
{"level":"error","message":"failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"error"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}] MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"Error: MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at module.exports (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\startup\\db.js:20:11)"}
{"level":"error","message":"failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"error"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}] MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"Error: MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at module.exports (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\startup\\db.js:20:11)"}
{"level":"error","message":"failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"error"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]"}
{"level":"error","message":"MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}] MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]","stack":"Error: MongoNetworkError: failed to connect to server [cluster0-shard-00-02.hbydh.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02.hbydh.mongodb.net:27017 closed\n    at TLSSocket.<anonymous> (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:372:9)\n    at Object.onceWrapper (events.js:309:26)\n    at TLSSocket.emit (events.js:219:5)\n    at net.js:666:12\n    at TCP.done (_tls_wrap.js:488:7) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at module.exports (C:\\Users\\user\\Projects\\NodeProjects\\ShopApi\\startup\\db.js:20:11)"}
